# Generated by Django 4.1.4 on 2023-01-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
